export const DEVELOPER_LIST_REQUEST = "DEVELOPER_LIST_REQUEST"
export const DEVELOPER_LIST_SUCCESS = "DEVELOPER_LIST_SUCCESS"
export const DEVELOPER_LIST_FAIL = "DEVELOPER_LIST_FAIL"

export const HOBBIES_LIST_REQUEST = "HOBBIES_LIST_REQUEST"
export const HOBBIES_LIST_SUCCESS = "HOBBIES_LIST_SUCCESS"
export const HOBBIES_LIST_FAIL = "HOBBIES_LIST_FAIL"

export const SELF_LIST_REQUEST = "SELF_LIST_REQUEST"
export const SELF_LIST_SUCCESS = "SELF_LIST_SUCCESS"
export const SELF_LIST_FAIL = "SELF_LIST_FAIL"